# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Pu t parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    message: 'you are fucking great!'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: false      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $message: '%message%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # Make all Controllers a service
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    app.greeting:
        class: App\Service\Greeting
        arguments:
            $logger: '@monolog.logger'
#            $message: '%message%'

    App\Service\Greeting: '@app_service.greeting'

    App\Controller\BlogController:
        arguments: ['@app.greeting', '@twig', '@.session.do-not-use', '@router.default']
        tags: ['controller.service_arguments']

    App\Controller\SecurityController:
        arguments: ['@app.greeting', '@twig', '@.session.do-not-use', '@router.default']
        tags: ['controller.service_arguments']

    App\Controller\MicroPostController:
        arguments: [
            '@twig',
            '@App\Repository\MicroPostRepository',
            '@Symfony\Component\Form\FormFactoryInterface',
            '@doctrine.orm.default_entity_manager',
            '@Symfony\Component\Routing\RouterInterface',
            '@Symfony\Component\HttpFoundation\Session\Flash\FlashBagInterface'
        ]
        tags: ['controller.service_arguments']

    App\Repository\MicroPostRepository: ['@Doctrine\Persistence\ManagerRegistry']

    app.command.hello:
        class: App\Command\HelloCommand
        arguments:
            $greeting: '@app.greeting'
        tags: ['console.command']

    App\Twig\AppExtension:
        arguments:
            $message: '%message%'
        tags: ['twig.extension']

    App\DataFixtures\AppFixtures: ['@Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface']
